### PR TITLE
use pylint for syntax checks

### PR DESCRIPTION
**Pull request by cholin**
We want to use continuous integration for syntax quality checks. This changeset
configures travis ci in combination with pylint to check our code for each pull
request.

### CODE REVIEW

**Comment by fupduck** [comment]
we should add pylint_django to requirements.txt
and use pylint 
actionmaps_backend maps manage.py --load-plugins pylint_django

this resolves at least the import errors.

**Comment by cholin** [comment]
You linked *django-lint* but used [pylint-django](https://github.com/landscapeio/pylint-django). I added the pylint-django plugin and some fixed some warnings. Maybe we should reenable the missing docstring error.

**Comment by fupduck** [comment]
we should use ` pylint actionmaps_backend maps --load-plugins pylint_django` checking manage.py gives errors not created by us

**Comment by cholin** [comment]
But I already did this in bd4773bce394e67ea130aa6c0d699eeee26b3e27 didn't I?

**Comment by cholin** [comment]
For pylint complains about the following issues:

```
************* Module actionmaps_backend.urls
C: 22, 0: Invalid constant name "router" (invalid-name)
C: 25, 0: Invalid constant name "prefix" (invalid-name)
************* Module actionmaps_backend.wsgi
C: 16, 0: Invalid constant name "application" (invalid-name)
************* Module maps.v1_views
I: 10, 0: Locally disabling no-member (E1101) (locally-disabled)
I: 20, 0: Locally disabling no-member (E1101) (locally-disabled)
************* Module maps.admin
W:  1, 0: Unused admin imported from django.contrib (unused-import)
************* Module maps.models
I:  8, 0: Locally disabling no-member (E1101) (locally-disabled)
W: 13, 0: No __unicode__ method on model (Map) (model-missing-unicode)
W: 25, 0: No __unicode__ method on model (Feature) (model-missing-unicode)
************* Module maps.tests
W:  1, 0: Unused TestCase imported from django.test (unused-import)
```

Global evaluation rates our code with `9.25/10`.

**Comment by fupduck** [comment]
year sry forget my previous comments. i'm a little confused atm.

**Comment by fupduck** [comment]
Looks fine. Will merge it and open another pull request for failing test cases.

**Pull request merged**
